# Generated by Django 3.2.7 on 2021-09-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='reply_text')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='blog.post')),
            ],
        ),
    ]
