# Generated by Django 3.2.7 on 2021-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_recipevideo_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipevideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='recipevideo',
            name='link',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
