# Generated by Django 3.2.7 on 2021-09-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipevideo',
            name='link',
        ),
    ]
