# Generated by Django 3.2.7 on 2021-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210926_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipevideo',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='RecipeVideo',
        ),
    ]
