# Generated by Django 3.2.7 on 2021-09-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Men'), ('female', 'Female'), ('Another', 'another')], max_length=255),
        ),
    ]
